### ISSUE TITLE
Custom data processing.

### ISSUE THREAD

**Issue by BPAWD** [chiehwangs/gaussian-head#7]
Hi, thanks for open-sourcing this good work. How to apply this method to a custom dataset? Could you provide the data processing code?

**Comment by chiehwangs** [comment]
> Hi, thanks for open-sourcing this good work. How to apply this method to a custom dataset? Could you provide the data processing code?

Hi,

Our work is conducted on a public dataset, with everything except the binary mask coming from NeRFBlendShape; you may want to refer to it for more details.

Furthermore, the only intricate parameter pertains to facial expressions. I am confident that facial expressions fitted by other 3DMM (such as BFM or FLAME) can also be utilized, but due to differences in dimensionality, it might require additional parameter adjustments to achieve optimal results.

I hope this information will assist you.

**Comment by BPAWD** [comment]
Thanks for your prompt reply! Any tips for adjusting the parameters for other 3DMM like FLAME? BTW, do you have a timeline for releasing the training code? Thanks.

**Comment by chiehwangs** [comment]
> Thanks for your prompt reply! Any tips for adjusting the parameters for other 3DMM like FLAME? BTW, do you have a timeline for releasing the training code? Thanks.

Hi,

1. I think using expressions from other 3DMMs is kind of an experimental thing, not really getting into theoretical changes. So, you can try tweaking the network complexity or using specific training tricks. Unfortunately, I haven't experimented a lot in this area, just tested out some feasibility. In past research, many projects have used diverse expression sources, like *'NerFace'* using face2face, *'IMavatar'* using FLAME, and so on. You can check those out to see how they play with expressions differently. 

2. The release date for our `train.py` is still up in the air, but I don't think it will be too long.

**Comment by Tiandishihua** [comment]
> Hi, thanks for open-sourcing this good work. How to apply this method to a custom dataset? Could you provide the data processing code?

Have you made your own dataset?

**Comment by chiehwangs** [comment]
> > Hi, thanks for open-sourcing this good work. How to apply this method to a custom dataset? Could you provide the data processing code?
> 
> Have you made your own dataset?

Reference  AD-NeRF
